---
  - name: Install Apache
    become: true
    yum:
      name: ["httpd"]
      state: latest
      update_cache: yes
  
  - name: Install index page
    copy:
      src: index.html
      dest: /var/www/html/index.html
      backup: yes
